### ISSUE TITLE
Update to docs on former LAB 3 & Documentation review for "Spark"

### ISSUE THREAD

**Issue by frspikke** [CiscoDevNet/devnet-express-cloud-collab-issues#30] opened 2020-04-22 13:40 UTC
<html>
<head>
<meta charset="utf8">
<title>Space Widget Demo</title>
<link rel="stylesheet" href="https://code.s4d.io/widget-space/production/main.css">
</head>
<body>
<div style="width: 500px; height: 500px;"
data-toggle="webex-space"
data-access-token="<your access token>"
data-destination-id="<to e-mail>"
data-destination-type="email"
/>
<script src="https://code.s4d.io/widget-space/production/bundle.js"></script>
</body>
</html>

Documentation review/update required for all labs changing from spark to Webex 🙂
Reference: https://developer.cisco.com/learning/tracks/devnet-express-cloud-collab-it-pro/business-value-itp/collab-business-sparksdk-widgets-itp/step/3 (wrong code)

**Comment by klevenstein** [comment] 2020-04-22 13:51
Duplicate of #31; will track fixes there.

**Closed as completed** 2020-04-22 13:51 UTC
Labels: duplicate
